// <auto-generated> Regenerates BusIds enum from the active BusGraphAsset. </auto-generated>
#if UNITY_EDITOR
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;
using DataOrientedAudio.Busses.Authoring;

namespace DataOrientedAudio.Busses.Editor
{
    public static class BusEnumGenerator
    {
        // Ensure this path is under the RUNTIME asmdef that consumes the enum.
        private const string OutputPath = "Assets/Scripts/Audio/Busses/Generated/BusIds.gen.cs";

        [MenuItem("Audio/Regenerate Bus Enum")]
        public static void Regenerate()
        {
            var assetGuid = AssetDatabase.FindAssets("t:BusGraphAsset").FirstOrDefault();
            if (string.IsNullOrEmpty(assetGuid))
            {
                Debug.LogWarning("No BusGraphAsset found.");
                return;
            }

            var path = AssetDatabase.GUIDToAssetPath(assetGuid);
            var graph = AssetDatabase.LoadAssetAtPath<BusGraphAsset>(path);
            if (graph == null || graph.buses == null || graph.buses.Length == 0)
            {
                Debug.LogWarning("BusGraphAsset has no buses.");
                return;
            }

            // Enforce Master at index 0 in the generated enum ordering.
            var busesOrdered = graph.buses
                .Select((b, i) => new { bus = b, index = i })
                .OrderBy(x => x.index) // keep serialized order
                .ToList();

            if (!string.Equals(busesOrdered[0].bus.name, "Master"))
            {
                Debug.LogWarning("First bus is not 'Master'. The baker should enforce this; enum will still generate.");
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> Do not edit. Generated from BusGraphAsset. </auto-generated>");
            sb.AppendLine("namespace DataOrientedAudio.Busses.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public enum BusId : ushort");
            sb.AppendLine("    {");

            var usedNames = new System.Collections.Generic.HashSet<string>();
            
            for (int i = 0; i < busesOrdered.Count; i++)
            {
                var name = busesOrdered[i].bus.name;
                if (string.IsNullOrWhiteSpace(name))
                    name = $"Bus{i}";
                    
                name = SanitizeEnumName(name, usedNames);
                sb.AppendLine($"        {name} = {i},");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            Directory.CreateDirectory(Path.GetDirectoryName(OutputPath)!);
            File.WriteAllText(OutputPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(OutputPath);
            Debug.Log($"Regenerated BusIds enum → {OutputPath}");
        }

        private static string SanitizeEnumName(string raw, System.Collections.Generic.HashSet<string> usedNames)
        {
            // Simple sanitize: remove spaces, non-letters/digits, ensure leading letter.
            var filtered = new string(raw.Where(char.IsLetterOrDigit).ToArray());
            if (string.IsNullOrEmpty(filtered)) filtered = "Bus";
            if (!char.IsLetter(filtered[0])) filtered = "Bus" + filtered;
            
            // Ensure uniqueness by appending numeric suffix if needed
            string uniqueName = filtered;
            int suffix = 2;
            while (usedNames.Contains(uniqueName))
            {
                uniqueName = $"{filtered}_{suffix}";
                suffix++;
            }
            
            usedNames.Add(uniqueName);
            return uniqueName;
        }
    }
}
#endif
